version: '3.8'

services:
  ollama-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_API_HOST=http://ollama:11434
      - NODE_ENV=production
      - AUTH_ENABLED=${AUTH_ENABLED:-false}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - ollama-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - ollama-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ulimits:
      memlock: -1
      stack: 67108864

networks:
  ollama-network:
    driver: bridge
    name: ollama-network

volumes:
  ollama_data:
    driver: local 